---
abstract: 'Pod::Weaver configuration the way DOHERTY does it'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.102400'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-PluginBundle-DOHERTY
requires:
  Pod::Weaver::Config::Assembler: 0
  Pod::Weaver::Plugin::Encoding: 0
  Pod::Weaver::Section::Availability: 1.102570
  Pod::Weaver::Section::BugsAndLimitations: 1.102670
  Pod::Weaver::Section::SourceGitHub: 0.53
  perl: 5.006
resources:
  bugtracker: http://github.com/doherty/Pod-Weaver-PluginBundle-DOHERTY/issues
  repository: git://github.com/doherty/Pod-Weaver-PluginBundle-DOHERTY.git
version: 0.002
